server:
  port: 9001
  

cloud:
  aws:
    credentials:
      access-key: <<ACCESS_KEY>>
      secret-key: <<SECRET_KEY>>
      useDefaultAwsCredentialsChain: true
    region:
      static: <<REGION>>
      auto: false
    stack:
      auto: false
    end-point:
      uri: <<AWS_QUEUE_URL>>
    queue:
      name: <AWS_QUEUE_NAME>
    dlc:
      uri: <<AWS_DLC_QUEUE>>

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:email_service;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

email-system-sender:
  address: <<SENDER_ID>>
  name: <<NAME>>

resilience4j:
  circuit-breaker:
    failure-rate-threshold: 50
    duration-in-open-state-ms: 2000
    ring-buffer-size-half-open-state: 10
    ring-buffer-size-closed-state: 100
  retry:
    max-attempts: 2
    wait-duration-ms: 500


