server:
  port: 9001
  

cloud:
  aws:
    region:
      static: <<REGION>>
      auto: false
    stack:
      auto: false
    end-point:
      uri: <<QUEUE_URI>>
    queue:
      name: <<QUEUE_NAME>>
    dlc:
      uri: <<DLC_QUEUE_URI>>

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:email_service;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

email-system-sender:
  address: <<SYS_ADMIN_MAIL_ID>>
  name: <<SYS_ADMIN_NAME>>

email-service-provider:
  mail-gun:
    uri: <<MAIL_GUN_URI>>
    username: <<MAIL_GUN_USERNAME>>
    password: <<MAIL_GUN_PASSWORD>>

  spark-post:
    uri: <<SPARK_POST_URI>
    authorization-code: <<SPARK_AUTHENTICATION_CODE>>

resilience4j:
  circuit-breaker:
    failure-rate-threshold: 50
    duration-in-open-state-ms: 2000
    ring-buffer-size-half-open-state: 10
    ring-buffer-size-closed-state: 100
  retry:
    max-attempts: 2
    wait-duration-ms: 500


